#!/bin/bash

dingpa_crawl.py gov.conf gov.db 0 10 &
dingpa_crawl.py gov.conf gov.db 1 10 &
dingpa_crawl.py gov.conf gov.db 2 10 &
dingpa_crawl.py gov.conf gov.db 3 10 &
dingpa_crawl.py gov.conf gov.db 4 10 &
dingpa_crawl.py gov.conf gov.db 5 10 &
dingpa_crawl.py gov.conf gov.db 6 10 &
dingpa_crawl.py gov.conf gov.db 7 10 &
dingpa_crawl.py gov.conf gov.db 8 10 &
dingpa_crawl.py gov.conf gov.db 9 10 &

wait